version: '3'

services:
  web-api:
    build: ./Rest API
    volumes:
      - ./Rest API:/api
    ports:
      - 3000:3000
  
  react-app:
    build: ./React JS
    volumes:
      - ./React JS:/app
    ports:
      - 80:80
    depends_on:
      - web-api